name: "Doc Viewer"
description: >-
  Serve documentation in /config/docs.
version: "1.7.16"
slug: "doc-viewer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
panel_icon: mdi:cube-outline
panel_iframe: true
ingress: true
ingress_port: 8000
# mount /config/doc folder into container
map:
  - type: homeassistant_config
    read_only: False
    path: /config
