name: "Doc Viewer"
description: >-
  Serve documentation in /config/docs.
version: "1.7.11"
slug: "doc-viewer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
panel_icon: mdi:cube-outline
# ingress: true
# ingress_port: 8000
webui: "http://[HOST]:[PORT:8000]"
# mount /config/doc folder into container
map:
  - type: homeassistant_config
    read_only: False
    path: /config
