name: "Doc Viewer"
description: >-
  Serve documentation in /config/docs.
version: "1.8.4"
slug: "doc-viewer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

# mount /config/doc folder into container
map:
  - type: homeassistant_config
    read_only: False
    path: /config
# webui: "http://[HOST]:[PORT:8000]"
# ports:
#   8000/tcp: 8000
# auth_api: true

ingress: true
ingress_port: 8000